import speech_recognition as sr

r = sr.Recognizer()

with sr.Microphone() as source:
    print("Talk")
    audio = r.listen(source)
    print("Time over, thanks")
    
try:
    print("Text: "+r.recognize_google(audio))
except:
    print("Sorry, I did not get that")

def convert_morse (code):

    code = code.replace("a",".-")
    code = code.replace("b","-...")
    code = code.replace("c","-.-.")
    code = code.replace("d","-..-")
    code = code.replace("e",".")
    code = code.replace("f","..-.")
    code = code.replace("g","--.")
    code = code.replace("h","....")
    code = code.replace("i","..")
    code = code.replace("j",".---")
    code = code.replace("k","-.-")
    code = code.replace("l",".-..")
    code = code.replace("m","--")
    code = code.replace("n","-.")
    code = code.replace("o","---")
    code = code.replace("p",".--.")
    code = code.replace("q","--.-")
    code = code.replace("r",".-.")
    code = code.replace("s","...")
    code = code.replace("t","-")
    code = code.replace("u","..-")
    code = code.replace("v","...-")
    code = code.replace("w",".--")
    code = code.replace("x","-..-")
    code = code.replace("y","-.--")
    code = code.replace("z","--..")

    code = code.replace("A",".-")
    code = code.replace("B","-...")
    code = code.replace("C","-.-.")
    code = code.replace("D","-..-")
    code = code.replace("E",".")
    code = code.replace("F","..-.")
    code = code.replace("G","--.")
    code = code.replace("H","....")
    code = code.replace("I","..")
    code = code.replace("J",".---")
    code = code.replace("K","-.-")
    code = code.replace("L",".-..")
    code = code.replace("M","--")
    code = code.replace("N","-.")
    code = code.replace("O","---")
    code = code.replace("P",".--.")
    code = code.replace("Q","--.-")
    code = code.replace("R",".-.")
    code = code.replace("S","...")
    code = code.replace("T","-")
    code = code.replace("U","..-")
    code = code.replace("V","...-")
    code = code.replace("W",".--")
    code = code.replace("X","-..-")
    code = code.replace("Y","-.--")
    code = code.replace("Z","--..")

    code = code.replace("1",".----")
    code = code.replace("2","..---")
    code = code.replace("3","...--")
    code = code.replace("4","....-")
    code = code.replace("5",".....")
    code = code.replace("6","-....")
    code = code.replace("7","--...")
    code = code.replace("8","---..")
    code = code.replace("9","----.")
    code = code.replace("0","-----")

    code = code.replace(",","--..--")
    code = code.replace(".",".-.-.")
    code = code.replace("?","..--..")
    code = code.replace("/","-..-.")
    code = code.replace("-","-....-")
    code = code.replace("(","-.--.")
    code = code.replace(")","-.--.-")

    return code

msg = r.recognize_google(audio)
print(f"initial code :{msg}")
morse = convert_morse(msg)
print(f"morse code: {morse}")
